name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA (with logs)
    runs-on: macos-14 # macOS runner with Xcode 15 and iOS 17 SDK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version (iOS 17 compatibility)
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app || sudo xcode-select -s /Applications/Xcode_15.app
          xcodebuild -version

      - name: Install CocoaPods (if using .xcworkspace)
        run: |
          if [ -f explt.xcworkspace ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Build and archive the app (with logging)
        run: |
          LOG=$RUNNER_TEMP/archive.log
          xcodebuild \
            -project explt.xcodeproj \
            -scheme explt \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $RUNNER_TEMP/explt.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            | tee "$LOG"

          echo '### Build Archive Log' >> $GITHUB_STEP_SUMMARY
          echo '```
          tail -n 50 "$LOG" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Package unsigned IPA manually (with logging)
        run: |
          LOG=$RUNNER_TEMP/export.log

          APP_NAME="explt"
          XCARCHIVE="$RUNNER_TEMP/explt.xcarchive"
          APP_PATH="$XCARCHIVE/Products/Applications/$APP_NAME.app"
          PAYLOAD_DIR="$RUNNER_TEMP/Payload"
          IPA_PATH="$RUNNER_TEMP/${APP_NAME}-unsigned.ipa"

          echo "➡️ App path: $APP_PATH" | tee "$LOG"

          if [ ! -d "$APP_PATH" ]; then
            echo "❌ .app not found at: $APP_PATH" | tee -a "$LOG"
            exit 1
          fi

          mkdir -p "$PAYLOAD_DIR"
          cp -r "$APP_PATH" "$PAYLOAD_DIR"

          cd $RUNNER_TEMP
          zip -r "$IPA_PATH" Payload >> "$LOG" 2>&1

          echo "✅ Finished creating IPA: $IPA_PATH" | tee -a "$LOG"

          echo '### IPA Packaging Log' >> $GITHUB_STEP_SUMMARY
          echo '```
          tail -n 50 "$LOG" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: ${{ runner.temp }}/explt-unsigned.ipa
          retention-days: 7

      - name: Upload Xcode logs
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs
          path: |
            ${{ runner.temp }}/archive.log
            ${{ runner.temp }}/export.log
          retention-days: 7
