name: Build explt - Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build_unsigned:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Install CocoaPods if .xcworkspace exists
        run: |
          if [ -f explt.xcworkspace ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Build unsigned xcarchive
        run: |
          xcodebuild \
            -project explt.xcodeproj \
            -scheme explt \
            -sdk iphoneos \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath $RUNNER_TEMP/explt.xcarchive \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Manually create unsigned IPA
        run: |
          APP_PATH="$RUNNER_TEMP/explt.xcarchive/Products/Applications/explt.app"
          PAYLOAD_DIR="$RUNNER_TEMP/Payload"
          IPA_PATH="$RUNNER_TEMP/explt-unsigned.ipa"

          mkdir -p "$PAYLOAD_DIR"
          cp -r "$APP_PATH" "$PAYLOAD_DIR"
          cd "$RUNNER_TEMP"
          zip -r "explt-unsigned.ipa" Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: explt-unsigned-ipa
          path: ${{ runner.temp }}/explt-unsigned.ipa
          retention-days: 7
