name: Build Unsigned IPA

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build:
    name: Build IPA
    runs-on: macos-14  # Xcode 15+, iOS 17+ SDK preinstalled

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version (iOS 17 compatibility)
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app || sudo xcode-select -s /Applications/Xcode_15.app
          xcodebuild -version

      - name: Install CocoaPods (if using .xcworkspace)
        run: |
          if [ -f explt.xcworkspace ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Build and archive the app (unsigned)
        run: |
          xcodebuild \
            -project explt.xcodeproj \
            -scheme explt \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $RUNNER_TEMP/explt.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO

      - name: Export unsigned IPA using local ExportOptions.plist
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $RUNNER_TEMP/explt.xcarchive \
            -exportPath $RUNNER_TEMP/build \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: ${{ runner.temp }}/build/*.ipa
          retention-days: 7
