name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    name: Build IPA (with logs)
    runs-on: macos-14 # macOS runner with Xcode 15 and iOS 17 SDK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version (iOS 17 compatibility)
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app || sudo xcode-select -s /Applications/Xcode_15.app
          xcodebuild -version

      - name: Install CocoaPods (if using .xcworkspace)
        run: |
          if [ -f explt.xcworkspace ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Build and archive the app (with logging)
        run: |
          LOG=$RUNNER_TEMP/archive.log
          xcodebuild \
            -project explt.xcodeproj \
            -scheme explt \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $RUNNER_TEMP/explt.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            | tee "$LOG"
          
          echo '### Build Archive Log' >> $GITHUB_STEP_SUMMARY
          echo '```
          tail -n 50 "$LOG" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Export unsigned IPA (with logging)
        run: |
          LOG=$RUNNER_TEMP/export.log
          xcodebuild \
            -exportArchive \
            -archivePath $RUNNER_TEMP/explt.xcarchive \
            -exportPath $RUNNER_TEMP/build \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO \
            | tee "$LOG"

          echo '### IPA Export Log' >> $GITHUB_STEP_SUMMARY
          echo '```
          tail -n 50 "$LOG" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: ${{ runner.temp }}/build/*.ipa
          retention-days: 7

      - name: Upload Xcode logs
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs
          path: |
            ${{ runner.temp }}/archive.log
            ${{ runner.temp }}/export.log
          retention-days: 7
